### ISSUE TITLE
windos11 run pnpm dev an error occurred  ：  is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Zourunfa** [Uninen/tauri-vue-template#23]
![image](https://user-images.githubusercontent.com/51783403/227845703-40cae785-2034-4e23-8157-1241f6502237.png)

**Comment by Uninen** [comment]
I don't have access to a Windows machine but I guess the problem with the command is in the setting of the env variable. Try changing [the dev command](https://github.com/Uninen/tauri-vue-template/blob/main/package.json#L6) from `"RUST_BACKTRACE=1 concurrently -k \"tauri dev\" \"pnpm devtools\"",` to `"concurrently -k \"tauri dev\" \"pnpm devtools\"",` and set the env variable manually.

**Comment by Zourunfa** [comment]
![image](https://user-images.githubusercontent.com/51783403/232226529-2ac0a527-6f29-46c2-8376-7aca9edb0a43.png)
I have installed the above one and solved my problem. Thank you
