### ISSUE TITLE
Issue with devtools

### ISSUE THREAD

**Issue by Uninen** [Uninen/tauri-vue-template#38]
> RollupError: "default" is not exported by "node_modules/.pnpm/@vue+devtools@7.0.2_vite@5.0.7

https://github.com/Uninen/tauri-vue-template/actions/runs/7524555427/job/20479550839

**Comment by aoor9** [comment]
```
main.ts 
import devtools from '@vue/devtools' // error
import { devtools } from '@vue/devtools' // correct
```

**Comment by Uninen** [comment]
Thanks a bunch! It's kinda trippy that Vue developers created a totally new project in a new repo and just pushed it into the same namespace on NPM 😅

I'll push a fix to this during the weekend 👍
