### ISSUE TITLE
App has a bunch of random text?

### ISSUE THREAD

**Issue by 9021007** [Uninen/tauri-vue-template#55]
I was looking at the binary release in a hex viewer, and apparently it includes Ireland... among a bunch of other random stuff. No idea why.

![image](https://github.com/Uninen/tauri-vue-template/assets/24487638/31c39a4e-3aac-4ece-ae51-b184e595fa71)

Nothing against the Irish, it's just that... why?
Oh and it also has stuff on Oxford college, the Library of Congress, and Colombia. 

It seems to have just a bunch of nonsense.

**Comment by 9021007** [comment]
What do you mean? I just opened the Mac app from the releases tab in a hex editor.

**Comment by Uninen** [comment]
Not sure how to repro nor test this so closing. If you find a way to expose this as an issue in the codebase with a test or clear steps to repro, I'll consider reopening.
